import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/Layout/CenterLayout'
import Header from '../components/Header'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'

const Dashboard: NextPage = () => {
  const router = useRouter()

  const { data: session, status } = useSession()

  console.log(session, status);
  
  if (status === "unauthenticated") {
    router.push('/')
  } else if(!session && status === "loading") {
    return <p>Loading...</p>
  } 

  return (
    <Layout>
      <Head>
        <title>React table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </Layout>
  )
}

export default Dashboard
